# Generated by Django 4.2.7 on 2023-12-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaint", "0002_alter_user_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="mobile",
            new_name="phone",
        ),
    ]
