# Generated by Django 4.2.7 on 2023-12-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaint", "0004_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
    ]
