# Generated by Django 4.2.7 on 2023-12-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaint", "0005_remove_user_phone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
